twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@ui/form/harmonyui_layout.html.twig'
    globals:
        tracking:
            enabled: '%tracking.enabled%'
            ga4_id: '%tracking.ga4_id%'

when@test:
    twig:
        strict_variables: true
