
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    restart: unless-stopped
    volumes:
      - .:/app
      - ../../packages:/app/packages
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      SERVER_NAME: :80
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}$$
    ports:
      - "8080:80"
