textarea:
  base:
    - "border-input transition-[color,box-shadow] outline-none flex field-sizing-content min-h-16 w-full rounded-md border bg-transparent px-3 py-2 text-base shadow-xs"
    - "placeholder:text-muted-foreground"
    - "selection:bg-primary selection:text-primary-foreground"
    - "dark:bg-input/30"
    - "disabled:cursor-not-allowed disabled:opacity-50"
    - "md:text-sm"
    - "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]"
    - "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive"
