services:
    ui.style_loader:
        class: HarmonyUi\Bundle\Style\StyleLoader

    ui.style_registry:
        class: HarmonyUi\Bundle\Style\StyleRegistry
        arguments:
            - '%ui.map%'
            - '%ui.tailwind_merge_enabled%'

    ui.component_props_parser:
        class: HarmonyUi\Bundle\Twig\ComponentPropsParser
        arguments:
            - '%kernel.project_dir%/vendor/harmonyui/ui-bundle/templates/components'

    ui.twig_extension:
        class: HarmonyUi\Bundle\Twig\StyleExtension
        arguments:
            - '@ui.style_registry'
            - '@ui.component_props_parser'
        tags:
            - twig.extension