name: Deploy

on:
  push:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper context
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ruby (for Kamal)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Set up deployment environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "KAMAL_DESTINATION=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "KAMAL_DESTINATION=production" >> $GITHUB_ENV
          fi

      - name: Deploy to staging
        if: github.ref == 'refs/heads/dev'
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KAMAL_STAGING_HOST: ${{ secrets.KAMAL_STAGING_HOST }}
        run: |
          # Setup SSH  
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $KAMAL_STAGING_HOST >> ~/.ssh/known_hosts
          
          # Deploy with Kamal (uses environment variables)
          cd apps/docs
          kamal deploy